# Generated by Django 6.0.7 on 2026-07-27 01:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("environments", "0003_environment_timezone"),
        ("tasks", "0004_occurrence_completed_at_occurrence_completed_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("actor_name", models.CharField(max_length=120)),
                (
                    "verb",
                    models.CharField(
                        choices=[
                            ("COMPLETED", "Concluiu"),
                            ("PICKED_UP", "Pegou"),
                            ("POSTPONED", "Adiou"),
                            ("ADDED_TASK", "Adicionou tarefa"),
                            ("AGENDA_CHANGED", "Mudou a agenda"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_events",
                        to="environments.environment",
                    ),
                ),
                (
                    "occurrence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_events",
                        to="tasks.occurrence",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
