# Generated by Django 6.0.7 on 2026-07-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_occurrence_completed_at_occurrence_completed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrence",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
    ]
