# Generated by Django 6.0.7 on 2026-07-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("environments", "0002_invitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="timezone",
            field=models.CharField(default="America/Sao_Paulo", max_length=64),
        ),
    ]
